language: cpp
compiler:
  - g++
before_install:
  - sh ./utilities/download_gtest.sh
  - sudo apt-get install libblas-dev libatlas-dev liblapack-dev
  - sh ./utilities/get_petsc.sh
script:
  - mkdir -p build
  - cd build
  - cmake -DLINDBLAD_BUILD_TESTS=ON -DPETSC_DIR=../petsc-cpucmplx ..
  - make
  - ctest --output-on-failure
  - rm -rf *
