virtualenv:
  system_site_packages: true
language: cpp
env:
  - CXX_="clang++"
  - CXX_="g++"
  - CXX_="g++-4.4"
  - CXX_="g++-4.8"
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq lcov
  - gem install coveralls-lcov
  - sudo apt-get install libblas-dev libatlas-dev liblapack-dev
  - sudo apt-get install -qq python-numpy
  - if [ "$CXX_" = "clang++" ]; then export CXX="clang++" CC=clang; fi
  - if [ "$CXX_" = "g++-4.4" ]; then sudo apt-get install -qq g++-4.4; fi
  - if [ "$CXX_" = "g++-4.4" ]; then export CXX="g++-4.4" CC="gcc-4.4"; fi
  - if [ "$CXX_" = "g++-4.8" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX_" = "g++-4.8" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - echo $CXX --version
  - sh ./utilities/download_gtest.sh
  - sh ./utilities/get_petsc.sh
script:
  - mkdir -p build
  - cd build
  - cmake -DLINDBLAD_BUILD_TESTS:BOOL=ON -DLINDBLAD_ENABLE_COVERAGE:BOOL=ON -DPETSC_DIR:PATH=../petsc-cpucmplx -DCMAKE_BUILD_TYPE:STRING=Debug -Dgtest_disable_pthres=ON ..
  - make
  - ctest --output-on-failure
after_success:
  - lcov -d tests -d src -d examples -base-directory .. -c -o coverage.info
  - lcov --remove coverage.info '/usr/*' -o coverage.info
  - lcov --remove coverage.info 'gtest*' -o coverage.info
  - lcov --remove coverage.info 'petsc-cpucmplx/*' -o coverage.info
  - cd ..
  - coveralls-lcov build/coverage.info
